#!/usr/bin/env python
# Copyright (c) 2009 Matt Harrison
import os
import sys
this_file = os.path.realpath(__file__)
module_dirname = os.path.dirname(this_file)
module_basename = os.path.basename(module_dirname)
elpa_base_dir = os.path.dirname(os.path.join(module_dirname, '..'))
cov2emacs_dir = os.path.join(elpa_base_dir, 'cov2emacslib')
if not os.path.exists(cov2emacs_dir):
    os.symlink(module_dirname, cov2emacs_dir)
sys.path.append(
    os.path.abspath(
        os.path.join(
            elpa_base_dir,
            '..')))
import cov2emacslib

if __name__ == '__main__':
    sys.exit(cov2emacslib.main(sys.argv))
